### ISSUE TITLE
Bump dependency for react 16

### ISSUE THREAD

**Issue by molszanski** [foxhound87/mobx-react-form-devtools#3]
Hey!

The package is not compatible with React 16 atm. 
But if you bump `reac-dock` version (0.2.3 -> 0.2.4) it will fix the PropTypes error.
[related issue](https://github.com/alexkuz/react-dock/pull/24)

**Comment by foxhound87** [comment]
Thanks for reporting this. 

I will release an update asap.

**Comment by molszanski** [comment]
Glad to help!
