### ISSUE TITLE
Prevent register() from being called more than once

### ISSUE THREAD

**Issue by marlonsupetran** [foxhound87/mobx-react-form-devtools#6]
Hello!

I just want to get your thoughts regarding the register() method. So I have this component that wraps the dev tool:
![image](https://user-images.githubusercontent.com/24822551/38436588-98aa740e-3a07-11e8-894e-37ecd8b17806.png)

I use it where I want the dev tool to display like this:
![image](https://user-images.githubusercontent.com/24822551/38436805-343e04da-3a08-11e8-973d-4e64ed656788.png)

This might not be an issue at all especially that it is only used for development, but is there a way to check if stores have been already registered, so that the register method is called only once?

Thanks!

**Comment by ethanyou725** [comment]
good point

**Comment by foxhound87** [comment]
you should call the methods outside the react component
