### ISSUE TITLE
Security Vulnerability caused by dependency to lodash@4.17.10

### ISSUE THREAD

**Issue by evarouss** [foxhound87/mobx-react-form-devtools#9]
A security vulnerability with a level of `high` is reported when running `npm audit` / `yarn audit`. 

![image](https://user-images.githubusercontent.com/365969/60288236-9ad45a80-98c8-11e9-980a-248f347434b4.png)

More info about the issue: https://www.npmjs.com/advisories/782
The issue is patched in `lodash>=4.17.11 `.

**Comment by foxhound87** [comment]
updated
